name: 'Crear tag'
description: 'Action para crear el tag personalizado para la imágen'
inputs:
  image_name:
    description: 'Nombre de la imagen'
    required: true
  version:
    description: 'Versión de la imagen'
    required: true
outputs:
  tag:
    description: 'tag final de la imagen'
    value: ${{ steps.generar-tag.outputs.tag }}
runs:
  using: "composite"
  steps:
    - name: Crear el tag
      id: generar-tag
      run: echo "tag=${{ env.user }}/${{ env.image }}:${{ env.version }}" >> $GITHUB_OUTPUT
      env:
        user: ${{ env.USERNAME }}
        image: ${{ inputs.image_name }}
        version: ${{ inputs.version }}
      shell: bash
