name: ci
on:
  workflow_call:
    outputs:
      tag:
        value: ${{ steps.tag.outputs.tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Obtener tag
        id: tag
        uses: ./.github/actions/getTag
        with:
          user: ${{ vars.DOCKER_USERNAME }}

      - name: login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.tag.outputs.tag }}


