name: ci
on: 
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Obtener versión'
        run: echo "version=$(jq -r '.version' ./package.json)" >> $GITHUB_ENV

        #- name: Obtener tag
        #id: tag
        #uses: ./.github/actions/getTag
        #with:
        #user: ${{ vars.DOCKER_USERNAME }}

      - name: login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ github.event.inputs.tag }}


