name: "trigger ci/cd"
on: push

jobs:
  ci:
    needs: tag
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  prueba:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.ci.outputs.tag }}

        #cd:
        #needs: ci
        #uses: ./.github/workflows/cd.yml
    #with: ${{ needs.tag.outputs.tag }}

