name: "trigger ci/cd"
on: push

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  cd:
    needs: ci
    uses: ./.github/workflows/cd.yml
    with: 
      tag: ${{ needs.ci.outputs.tag }}

