on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment

jobs:
  container-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ vars.prueba }}
