on: push
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: json
        uses: zvonimirsun/read-package-version-actions@v2
        id: version
      - run: echo "${{ steps.version.outputs.version }}
