on: workflow_dispatch

jobs:
  container-test:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - name: Coger repo
        uses: action/checkout@v4


    steps:
      - run: node --version
      - run: ls -la
      - run: cd /
      - run: ls -la
