on: push

jobs:
  container-test:
    runs-on: ubuntu-latest
    container:
      image: node
      volumes:
        - ${{ github.workspace }}:/
    steps:
      - run: ls -la
      - run: cd /
      - run: ls -la
